### ISSUE TITLE
Obtaining batch corrected cell fractions

### ISSUE THREAD

**Issue by ConDem94** [linxy29/DCATS#12]
Hi, thank you for this great package!

I am trying to perform differential compositional analysis across samples from different batches of pancreatic cancer single cell rna seq. I do not have a pre-defined variable for the comparison of cell fractions, but trying to perform clustering on all of the sub cluster fractions across all samples to identify main TME subtypes (cellular communities). 

Is there a way to use this package to remove batch effects on the cell fraction matrix before performing clustering?

Thank you!

**Comment by linxy29** [comment]
Hi @ConDem94 ,

DCATS is not applicable to remove the batch effect. DCATS is done after clustering when we have cell numbers of each cell type.
