### ISSUE TITLE
Small number of cell affecting high p-value?

### ISSUE THREAD

**Issue by parkjooyoung99** [linxy29/DCATS#14]
Dear developer, 

I am currently using DCAT for differential abundancy analysis and got the result that was hard to understand. 

If you see the below UMAP, it is so apparent that cluster 7 is enriched in AD compared to PSO. However, the DCAT fdr value is 0.3xx which is saying the comparison is not significant. 
![image](https://github.com/holab-hku/DCATS/assets/77565848/673c9fe2-1004-4521-8a14-af618a1e4521)

Does this result come from small number of PSO cells?

**Comment by linxy29** [comment]
Dear @parkjooyoung99,

Yes. DCATS will consider the proportion of each cell type among the overall cells in each condition. In this case, you have a small number of PSO cells and this will influence the final result.
