### ISSUE TITLE
How to interpret dcats_GLM function results

### ISSUE THREAD

**Issue by Yijia-Jiang** [linxy29/DCATS#15]
Hello, thank you for the tool. I run the tutorial compatible with seurat and have a question regarding results from dcats_GLM function.

Could you tell me what the coefficient, LR_vals, and LR_pvals mean? To reproduce figures in your paper, how did you calculate the proportion of cell types in condition A vs B? 

Thank you

**Comment by linxy29** [comment]
Hi Yijia,

1) coefficient indicates the change of mean proportions for each cell type when conditions change, LR_vals is the values of likelihood ratio test which is used to calculate LR_pvals. LR_pvals is the p-value of the likelihood ratio test. 

2) The proportions of cell types are calculated by using the number of cells in each cell type divided by the total number of cells in a sample.
