### ISSUE TITLE
knn_simMat Error

### ISSUE THREAD

**Issue by gianfilippo** [linxy29/DCATS#16]
Hi,
when I run knn_simMat on my Seurat object
knn_mat = knn_simMat(scdata@graphs$SNN,scdata$singleR)
I get the following error 
Error in KNN_matrix[idx_i, ][, idx_j] : incorrect number of dimensions

My scdata object is 
scdata
An object of class Seurat 
35285 features across 73877 samples within 2 assays 
Active assay: RNA (32285 features, 0 variable features)
 1 other assay present: integrated
 3 dimensional reductions calculated: pca, umap, tsne

my scdata@graphs$SNN
dim(scdata@graphs$SNN)
[1] 73877 73877

What am I doing wrong ?

Thanks

**Comment by linxy29** [comment]
Hi @gianfilippo ,
This problem might be caused by the scdata$singleR. Could you check 1) the dimension of scdata$singleR through `length(scdata$singleR)`; and the number of cell types that exist through `unique(scdata$singleR)`?

**Comment by gianfilippo** [comment]
Hi,
thanks. Not sure what happened. I tried with the full dataset and it worked.
Best
